name: ci
on:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      - run: |
          docker build -t ghcr.io/realash82/zz-jpeg-recompress-builder docker-builder --push
          docker build -t ghcr.io/realash82/zz-jpeg-recompress-bin docker-bin --push
